# Libraries ---------------------------------------------------------------


renv::install("units")
renv::install("purrr")
renv::install("dplyr")
renv::install("tidyr")
renv::install("stringr")
renv::install("lubridate")
renv::install("rdwd")
renv::install("zoo")
renv::install("xml2")
renv::install("readxl")
renv::install("zip")
renv::install("jsonlite")
renv::install("OSMscale")
renv::install("spsUtil")
renv::install("rlang")
renv::install("cropCalendars")
renv::install("DSSAT")
renv::install("rlang")
renv::install("countrycode")
renv::install("ggplot2")
