
# Libraries ---------------------------------------------------------------


install.packages("units")
install.packages("purrr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("stringr")
install.packages("lubridate")
install.packages("rdwd")
install.packages("zoo")
install.packages("xml2")
install.packages("readxl")
install.packages("zip")
install.packages("jsonlite")
install.packages("OSMscale")
install.packages("spsUtil")
install.packages("rlang")
install.packages("cropCalendars")
install.packages("DSSAT")
install.packages("rlang")
install.packages("countrycode")
install.packages("ggplot2")
