#' Estimate important phenological dates based on crop and weather data whenever they are missing from the input dataset
#' 
#' Maturity dates are estimated based on the approaches from Waha et al. (2012) and Minoli et al. (2019) implemented
#' in the package cropCalendars (https://github.com/AgMIP-GGCMI/cropCalendars/tree/master)
#' Currently only handles maize, rice, sorghum, soybean, and wheat. 
#' Anthesis date are currently estimated relative to maturity dates, using expert sources (temporary implementation).
#' Wheat: https://www.arvalis.fr/infos-techniques/stades-des-cereales-bientot-lepiaison
#' Maize: average difference from DSSAT default datasets (temperate)
#' 
#' @export
#'
#' @param sdata a dataframe containing the target summary observed data, as generated by reshape_exp_data
#' @param wdata a dataframe containing the weather data for the target year, as generated by get_weather
#' @param crop a string indicating the target crop [currently as ICASA standard coding, e.g. WHT, MAZ, etc.]
#' @param lat a numeric indicating the latitude of the target experimental field
#' @param lon a numeric indicating the longitude of the target experimental field
#' @param year a numeric indicating the target year
#' @param irrigated a logical indicating whether the target field was irrigated or not (i.e., rainfed)
#' 
#' @return the summary observed data with estimated phenological dates
#' 
#' @importFrom cropCalendars calcMonthlyClimate calcCropCalendars
#' @importFrom dplyr "%>%" filter
#' @importFrom lubridate as_date ymd
#' 


estimate_phenology <- function(sdata, wdata, crop, lat, lon, year, irrigated = FALSE){
  
  # Apply filters
  sdata <- sdata %>% filter(Year == year) ; sdata$MDAT <- ymd(sdata$MDAT)
  wdata <- wdata %>% filter(Year == year)
  irrigated <- ifelse(irrigated, "Irrigated", "Rainfed")  # TODO: add irrigation = TRUE
  
  # Calculate monthly climate
  d_temp <- matrix(wdata$TMEAN, nrow = 1) # string daily mean temperature; matrix with nyears rows and days cols
  d_prec <- matrix(wdata$RAIN, nrow = 1) # string daily sum precip
  
  mclim <- calcMonthlyClimate(lat = lat, temp = d_temp, prec = d_prec, syear = year, eyear = year,
                              incl_feb29 = leap_year(year)) 

  for (i in 1:nrow(sdata)){
    
    if (is.na(sdata$MDAT[i])) {
      
      if (grepl("WHT|WH|wheat|Wheat|BAR|BA|Barley|barley", crop)) {
        
        # TODO: check sowing date to separate spring and winter crops (same crop codes)
        calendar <- calcCropCalendars(lon = lon, lat = lat, mclimate = mclim, crop = "Winter_Wheat")
        calendar <- calendar[calendar$irrigation == irrigated,]
        
        mdat <- as_date(paste0(year, "-01-01")) + calendar$maturity_doy - 1 +
          sample(-3:3, 1, replace = TRUE)  # add some random variation
        adat <- as_date(mdat) - round(rnorm(1, mean = 40, sd = 5))  # WHT
        
        sdata$MDAT[i] <- as_date(mdat)
        sdata$ADAT[i] <- adat  # for loop coerces to vector, convert to date after
        
      } else if (grepl("MAZ|MZ|Maize|maize", crop)) {
        
        calendar <- calcCropCalendars(lon = lon, lat = lat, mclimate = mclim, crop = "Maize")
        calendar <- calendar[calendar$irrigation == irrigated,]
        
        mdat <- as_date(paste0(year, "-01-01")) + calendar$maturity_doy - 1 +
          sample(-3:3, 1, replace = TRUE)  # add some random variation
        adat <- as_date(mdat) - round(rnorm(1, mean = 50, sd = 5))  # MAZ
        
        sdata$MDAT[i] <- as_date(mdat)
        sdata$ADAT[i] <- adat  # for loop coerces to vector, convert to date after
        
      } else {
        
        sdata$MDAT[i] <- NA
        sdata$ADAT[i] <- NA
      }
      
    } else {
      
      mdat <- as_date(sdata$MDAT[i])
      adat <- as_date(mdat) - round(rnorm(1, mean = 40, sd = 5))

      sdata$MDAT[i] <- as_date(mdat)
      sdata$ADAT[i] <- adat  # for loop coerces to vector, convert to date after

    }
  }
  
  # Convert back to date format
  sdata$MDAT <- as_date(sdata$MDAT)
  sdata$ADAT <- as_date(sdata$ADAT)
  
  return(sdata)
}
